name: seek_flutter_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.12
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  json_serializable: ^6.9.0
  path: any
  sqflite: any

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^22.7.2

flutter:
  uses-material-design: true
